<?php 
$user = $this->identity();
?>

<div class="row">
	<div class="col-lg-12">
		<div class="box">
			<div class="box-header">
				<h2><i class="icon-edit"></i><?php echo $this->translate('Edit Profile')?></h2>
				
			</div>
			<div class="box-content">
				<form class="form-horizontal" method="post" action="<?php echo $this->basePath() ?>/admin/user/update"> 
				  <fieldset class="col-sm-12">	
					<div class="form-group">
					  <label class="control-label" for="login"><?php echo $this->translate('Your login:')?></label>
					  <div class="controls">
						 <input type="hidden" name="id" value="<?php echo $user->getId()?>" />
						 <input class="form-control disabled" id="login" name="login" type="text" placeholder="<?php echo $this->translate('Type your login...')?>" value="<?php echo $user->getLogin()?>" disabled="" />
					  </div>
					</div>
					
					<div class="form-group">
					  <label class="control-label" for="name"><?php echo $this->translate('Your name:')?></label>
					  <div class="controls">
						 <input class="form-control" id="name" name="name"  type="text" placeholder="<?php echo $this->translate('Type your name...')?>" value="<?php echo $user->getName()?>" />
					  </div>
					</div>
					
					<div class="form-group">
					  <label class="control-label" for="email"><?php echo $this->translate('Your e-mail:')?></label>
					  <div class="controls">
						 <input class="form-control" name="email"  type="text" placeholder="<?php echo $this->translate('Type your email...')?>" value="<?php echo $user->getEmail()?>" />
					  </div>
					</div>
					
					<div class="form-group">
						<label class="control-label" for="gender"><?php echo $this->translate('Gender')?></label>
						<div class="controls">
						  	<select id="gender" name="gender" class="form-control">
								<option value="_M_" <?php echo $user->getGender() == '_M_' ? 'selected="selected"':'' ?>><?php echo $this->translate('Male')?></option>
								<option value="_F_" <?php echo $user->getGender() == '_F_' ? 'selected="selected"':'' ?>><?php echo $this->translate('Female')?></option>
						  	</select>
						</div>
					</div>
											
					<div class="form-group">
					  <label class="control-label" for="fileInput"><?php echo $this->translate('Profile picture:')?></label>
					  <div class="controls">
						<input class="input-file uniform_on" id="fileInput" name="photofile" type="file">
					  </div>
					</div>          
				
					<div class="form-actions">
					  <button type="submit" class="btn btn-primary"><?php echo $this->translate('Save Changes')?></button>
					  <button type="reset" class="btn"><?php echo $this->translate('Cancel')?></button>
					</div>
				  </fieldset>
				</form>   

			</div>
		</div>
	</div><!--/col-->

</div><!--/row-->