<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Vende F&aacute;cil '. $this->translate('Compre e Venda de tudo pelo Celular'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendName('author', 'Olimpo Tecnologia')
            ->appendName('description', 'Pague a conta do bar, balada, restaurante pelo celular.
			Compre produtos nas vitrines das lojas via QRcode')
            ->appendName('keyword', 'vender,compra mobile, compra pelo celular, vender qrcode')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        
      
		
        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.min.css')
                        ->prependStylesheet($this->basePath() . '/css/retina.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>
	<style type="text/css">
			body { background: url(<?php echo $this->basePath()?>/img/bg-login.jpg) !important; }
		</style>
		
	<!-- The HTML5 shim, for IE6-8 support of HTML5 elements -->
	<!--[if lt IE 9]>
	  	<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<link id="ie-style" href="css/ie.css" rel="stylesheet">
	<![endif]-->
	
	<!--[if IE 9]>
		<link id="ie9style" href="css/ie9.css" rel="stylesheet">
	<![endif]-->
	
	
       
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Vende Facil') ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
          
            
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
         <!-- Scripts -->
  
    </body>
</html>
